name: Python
on:
  workflow_call:

jobs:
  python:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: pip3 install mypy pylint
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Check formatting
        uses: psf/black@stable
        with:
          options: "--check"
      - name: Run PyLint
        run: pylint . --msg-template="::error file={path},line={line},col={column},title={category}::({symbol}) {msg}"
      - name: Run MyPy
        run: mypy .
